# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dash_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DashAdmin(object):
    def setupUi(self, DashAdmin):
        DashAdmin.setObjectName("DashAdmin")
        DashAdmin.resize(796, 655)
        self.gridLayout = QtWidgets.QGridLayout(DashAdmin)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(DashAdmin)
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"border: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 637))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.welcome = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome.sizePolicy().hasHeightForWidth())
        self.welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("#welcome {\n"
"padding: 7px;\n"
"}")
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.gridLayout_2.addWidget(self.welcome, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setStyleSheet("#line{\n"
"border-top: 1px solid #4589e8;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 1)
        self.tests = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tests.sizePolicy().hasHeightForWidth())
        self.tests.setSizePolicy(sizePolicy)
        self.tests.setMinimumSize(QtCore.QSize(0, 400))
        self.tests.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tests.setStyleSheet("#tests{\n"
"background-color: #f7f7f7;\n"
"border: 0px;\n"
"}")
        self.tests.setWidgetResizable(True)
        self.tests.setObjectName("tests")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 648, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 600))
        self.scrollAreaWidgetContents_2.setStyleSheet("#scrollAreaWidgetContents_2 {\n"
"background: transparent\n"
"}")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.tests.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.tests, 3, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.newtest = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newtest.sizePolicy().hasHeightForWidth())
        self.newtest.setSizePolicy(sizePolicy)
        self.newtest.setStyleSheet("padding: 7px;")
        self.newtest.setObjectName("newtest")
        self.horizontalLayout_2.addWidget(self.newtest)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(DashAdmin)
        QtCore.QMetaObject.connectSlotsByName(DashAdmin)

    def retranslateUi(self, DashAdmin):
        _translate = QtCore.QCoreApplication.translate
        DashAdmin.setWindowTitle(_translate("DashAdmin", "Form"))
        self.welcome.setText(_translate("DashAdmin", "Welcome, Admin"))
        self.label.setText(_translate("DashAdmin", "Tests"))
        self.newtest.setText(_translate("DashAdmin", "New Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashAdmin = QtWidgets.QWidget()
    ui = Ui_DashAdmin()
    ui.setupUi(DashAdmin)
    DashAdmin.show()
    sys.exit(app.exec_())
