# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dash.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dash(object):
    def setupUi(self, Dash):
        Dash.setObjectName("Dash")
        Dash.resize(792, 655)
        self.gridLayout = QtWidgets.QGridLayout(Dash)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dash)
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"border: 0px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 757, 1084))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.welcome = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome.sizePolicy().hasHeightForWidth())
        self.welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("#welcome {\n"
"padding: 7px;\n"
"}")
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.gridLayout_2.addWidget(self.welcome, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.tests = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tests.sizePolicy().hasHeightForWidth())
        self.tests.setSizePolicy(sizePolicy)
        self.tests.setMinimumSize(QtCore.QSize(0, 400))
        self.tests.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tests.setStyleSheet("#tests{\n"
"background-color: #f7f7f7;\n"
"border: 0px;\n"
"}")
        self.tests.setWidgetResizable(True)
        self.tests.setObjectName("tests")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 627, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 600))
        self.scrollAreaWidgetContents_2.setStyleSheet("#scrollAreaWidgetContents_2 {\n"
"background: transparent\n"
"}")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.tests.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.tests, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 1, 1, 1)
        self.scoretab = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoretab.sizePolicy().hasHeightForWidth())
        self.scoretab.setSizePolicy(sizePolicy)
        self.scoretab.setMinimumSize(QtCore.QSize(0, 500))
        self.scoretab.setObjectName("scoretab")
        self.scoredash = QtWidgets.QWidget()
        self.scoredash.setStyleSheet("#scoredash, #allscores{\n"
"\n"
"background:#f7f7f7;\n"
"}")
        self.scoredash.setObjectName("scoredash")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scoredash)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scoredashlayout = QtWidgets.QHBoxLayout()
        self.scoredashlayout.setObjectName("scoredashlayout")
        self.horizontalLayout.addLayout(self.scoredashlayout)
        self.scoretab.addTab(self.scoredash, "")
        self.allscores = QtWidgets.QWidget()
        self.allscores.setStyleSheet("#allscores{\n"
"background:#f7f7f7;\n"
"}")
        self.allscores.setObjectName("allscores")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.allscores)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.allscores)
        self.scrollArea_2.setStyleSheet("#scrollArea_2 {\n"
"border: 0px;\n"
"}\n"
"\n"
"#scrollAreaWidgetContents_3{\n"
"background: #f7f7f7;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 603, 456))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.allscoreslayout = QtWidgets.QHBoxLayout()
        self.allscoreslayout.setObjectName("allscoreslayout")
        self.horizontalLayout_4.addLayout(self.allscoreslayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.scoretab.addTab(self.allscores, "")
        self.gridLayout_2.addWidget(self.scoretab, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("#label {\n"
"padding: 7px;\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setStyleSheet("#line{\n"
"border-top: 1px solid #4589e8;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(Dash)
        self.scoretab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dash)

    def retranslateUi(self, Dash):
        _translate = QtCore.QCoreApplication.translate
        Dash.setWindowTitle(_translate("Dash", "Form"))
        self.welcome.setText(_translate("Dash", "Welcome, <name>"))
        self.label_2.setText(_translate("Dash", "Scores"))
        self.scoretab.setTabText(self.scoretab.indexOf(self.scoredash), _translate("Dash", "Dashboard"))
        self.scoretab.setTabText(self.scoretab.indexOf(self.allscores), _translate("Dash", "All scores"))
        self.label.setText(_translate("Dash", "Available Tests"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dash = QtWidgets.QWidget()
    ui = Ui_Dash()
    ui.setupUi(Dash)
    Dash.show()
    sys.exit(app.exec_())
