# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questiontemp.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_questiontemp(object):
    def setupUi(self, questiontemp):
        questiontemp.setObjectName("questiontemp")
        questiontemp.resize(608, 322)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(questiontemp.sizePolicy().hasHeightForWidth())
        questiontemp.setSizePolicy(sizePolicy)
        questiontemp.setMinimumSize(QtCore.QSize(600, 300))
        questiontemp.setStyleSheet("#questiontemp {\n"
"background: #fff;\n"
"border: 1px solid #4589e8;\n"
"}\n"
"\n"
"QLineEdit {\n"
"border: 1px solid #ddd;\n"
"padding: 3px;\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(questiontemp)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(questiontemp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 87))
        self.groupBox.setStyleSheet("#groupBox {\n"
"border-top: 1px solid #4589e8;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.d = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.d.sizePolicy().hasHeightForWidth())
        self.d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.d.setFont(font)
        self.d.setText("")
        self.d.setObjectName("d")
        self.gridLayout_2.addWidget(self.d, 3, 0, 1, 1)
        self.c = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.c.sizePolicy().hasHeightForWidth())
        self.c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.c.setFont(font)
        self.c.setText("")
        self.c.setObjectName("c")
        self.gridLayout_2.addWidget(self.c, 2, 0, 1, 1)
        self.b = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.b.sizePolicy().hasHeightForWidth())
        self.b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.b.setFont(font)
        self.b.setText("")
        self.b.setObjectName("b")
        self.gridLayout_2.addWidget(self.b, 1, 0, 1, 1)
        self.a = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.a.sizePolicy().hasHeightForWidth())
        self.a.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.a.setFont(font)
        self.a.setText("")
        self.a.setObjectName("a")
        self.gridLayout_2.addWidget(self.a, 0, 0, 1, 1)
        self.atext = QtWidgets.QLineEdit(self.groupBox)
        self.atext.setObjectName("atext")
        self.gridLayout_2.addWidget(self.atext, 0, 1, 1, 1)
        self.btext = QtWidgets.QLineEdit(self.groupBox)
        self.btext.setObjectName("btext")
        self.gridLayout_2.addWidget(self.btext, 1, 1, 1, 1)
        self.ctext = QtWidgets.QLineEdit(self.groupBox)
        self.ctext.setObjectName("ctext")
        self.gridLayout_2.addWidget(self.ctext, 2, 1, 1, 1)
        self.dtext = QtWidgets.QLineEdit(self.groupBox)
        self.dtext.setText("")
        self.dtext.setObjectName("dtext")
        self.gridLayout_2.addWidget(self.dtext, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(questiontemp)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.questiontext = QtWidgets.QLineEdit(questiontemp)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.questiontext.setFont(font)
        self.questiontext.setStyleSheet("")
        self.questiontext.setObjectName("questiontext")
        self.gridLayout.addWidget(self.questiontext, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)

        self.retranslateUi(questiontemp)
        QtCore.QMetaObject.connectSlotsByName(questiontemp)

    def retranslateUi(self, questiontemp):
        _translate = QtCore.QCoreApplication.translate
        questiontemp.setWindowTitle(_translate("questiontemp", "Form"))
        self.atext.setPlaceholderText(_translate("questiontemp", "Insert Option A..."))
        self.btext.setPlaceholderText(_translate("questiontemp", "Insert Option B..."))
        self.ctext.setPlaceholderText(_translate("questiontemp", "Insert Option C..."))
        self.dtext.setPlaceholderText(_translate("questiontemp", "Insert Option D..."))
        self.label.setText(_translate("questiontemp", "1."))
        self.questiontext.setPlaceholderText(_translate("questiontemp", "Insert question text..."))
